version: '3.8'

services:
  web:
    build: .
    container_name: tienda-agil-web
    ports:
      - "9002:3000"
    restart: unless-stopped
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/tienda-agil
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: tienda-agil-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
