version: '3.8'

services:
  web:
    # Construye la imagen a partir del Dockerfile en el directorio actual (.)
    build: .
    # Nombra el contenedor para una fácil identificación
    container_name: tienda-agil-web
    # Mapea el puerto 9002 de tu máquina local al puerto 3000 del contenedor
    # donde corre la aplicación Next.js en producción.
    ports:
      - "9002:3000"
    # Reinicia el contenedor automáticamente si se detiene por alguna razón
    restart: unless-stopped
    # Define las variables de entorno que necesita la aplicación.
    # En este caso, el puerto que Next.js debe usar dentro del contenedor.
    environment:
      - PORT=3000
